/*
 * PainelEntrada.java
 *
 * Created on 8 de Agosto de 2007, 19:43
 */

package batalha.interfacegrafica;

/**
 *
 * @author  Usuario
 */
public class PainelEntrada extends javax.swing.JPanel {
    
    /** Creates new form PainelEntrada */
    public PainelEntrada() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Código Gerado ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jLApelidoJogo = new javax.swing.JLabel();
        jTxApelidoJogo = new javax.swing.JTextField();
        jLOpcaoJogo = new javax.swing.JLabel();
        jLIpsUtilizados = new javax.swing.JLabel();
        jCbIpsUtilizados = new javax.swing.JComboBox();
        jCkAdicionarIp = new javax.swing.JCheckBox();
        jTxNovoIp = new javax.swing.JTextField();
        jBtIniciarJogo = new javax.swing.JButton();
        jROpcaoServidor = new javax.swing.JRadioButton();
        jROpcaoCliente = new javax.swing.JRadioButton();

        jLApelidoJogo.setText("Apelido no Jogo:");

        jLOpcaoJogo.setText("Quero ser");

        jLIpsUtilizados.setText("IPs mais utilizados:");

        jCbIpsUtilizados.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jCkAdicionarIp.setText(" Quero adicionar um novo IP");
        jCkAdicionarIp.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jCkAdicionarIp.setMargin(new java.awt.Insets(0, 0, 0, 0));

        jTxNovoIp.setText("Digite aqui um novo IP para se conectar");

        jBtIniciarJogo.setText("JOGAR!");

        jROpcaoServidor.setText("Servidor");
        jROpcaoServidor.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jROpcaoServidor.setMargin(new java.awt.Insets(0, 0, 0, 0));

        jROpcaoCliente.setText("Cliente");
        jROpcaoCliente.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jROpcaoCliente.setMargin(new java.awt.Insets(0, 0, 0, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(338, 338, 338)
                .addComponent(jBtIniciarJogo, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(71, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTxNovoIp, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(80, 80, 80)
                                .addComponent(jLIpsUtilizados, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(11, 11, 11))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(70, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLApelidoJogo, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLOpcaoJogo, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(31, 31, 31)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTxApelidoJogo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jROpcaoServidor)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                                .addComponent(jROpcaoCliente))
                            .addComponent(jCbIpsUtilizados, javax.swing.GroupLayout.Alignment.LEADING, 0, 185, Short.MAX_VALUE)
                            .addComponent(jCkAdicionarIp, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE))))
                .addGap(164, 164, 164))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxApelidoJogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLApelidoJogo, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLOpcaoJogo, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jROpcaoServidor)
                    .addComponent(jROpcaoCliente))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLIpsUtilizados, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCbIpsUtilizados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addComponent(jCkAdicionarIp, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(jTxNovoIp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addComponent(jBtIniciarJogo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    
            
            
    
    // Declaração de variáveis - não modifique//GEN-BEGIN:variables
    private javax.swing.JButton jBtIniciarJogo;
    private javax.swing.JComboBox jCbIpsUtilizados;
    private javax.swing.JCheckBox jCkAdicionarIp;
    private javax.swing.JLabel jLApelidoJogo;
    private javax.swing.JLabel jLIpsUtilizados;
    private javax.swing.JLabel jLOpcaoJogo;
    private javax.swing.JRadioButton jROpcaoCliente;
    private javax.swing.JRadioButton jROpcaoServidor;
    private javax.swing.JTextField jTxApelidoJogo;
    private javax.swing.JTextField jTxNovoIp;
    // Fim da declaração de variáveis//GEN-END:variables
    
    public static void main (){
        PainelEntrada application = new PainelEntrada();
    }
}
