/*
 * PainelJogo.java
 *
 * Created on 19 de Agosto de 2007, 21:09
 */

package batalha.interfacegrafica;

import batalha.interfacegrafica.jogo.*;
import java.awt.LayoutManager;
import javax.swing.JTextField;
import javax.swing.SwingUtilities;

/**
 *
 * @author  Usuario
 */
public class PainelDoJogo extends javax.swing.JPanel {
    
    /** Creates new form PainelJogo */
    public PainelDoJogo() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Código Gerado ">                          
    private void initComponents() {
        
        tabuleiroOponente = new TabuleiroInimigo();
        jScrollPane1 = new javax.swing.JScrollPane();
        chat = new javax.swing.JTextArea();
        painelCentral = new javax.swing.JPanel();
        painelControle = new javax.swing.JPanel();
        btPoderEspecial = new javax.swing.JButton();
        painelLabelJogo = new javax.swing.JPanel();
        btEnviarMensagem = new javax.swing.JButton();
        areaDeConfiguracaoDeNavio = new AreaCentral(tabuleiroOponente);
        meuTabuleiro = new TabuleiroJogador(areaDeConfiguracaoDeNavio);
        dadosRede = new DadosRede();
        txfMensagem = new JTextField(110);
                
        meuTabuleiro.setBackground(new java.awt.Color(255, 0, 0));
        meuTabuleiro.setMaximumSize(new java.awt.Dimension(250, 250));
        meuTabuleiro.setMinimumSize(new java.awt.Dimension(250, 250));
        meuTabuleiro.setPreferredSize(new java.awt.Dimension(250, 250));
        javax.swing.GroupLayout meuTabuleiroLayout = new javax.swing.GroupLayout(meuTabuleiro);
        meuTabuleiro.setLayout(meuTabuleiroLayout);
        meuTabuleiroLayout.setHorizontalGroup(
            meuTabuleiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
        );
        meuTabuleiroLayout.setVerticalGroup(
            meuTabuleiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
        );

        tabuleiroOponente.setBackground(new java.awt.Color(255, 0, 0));
        tabuleiroOponente.setMaximumSize(new java.awt.Dimension(250, 250));
        tabuleiroOponente.setMinimumSize(new java.awt.Dimension(250, 250));
        tabuleiroOponente.setPreferredSize(new java.awt.Dimension(250, 250));
        javax.swing.GroupLayout tabuleiroOponenteLayout = new javax.swing.GroupLayout(tabuleiroOponente);
        tabuleiroOponente.setLayout(tabuleiroOponenteLayout);
        tabuleiroOponenteLayout.setHorizontalGroup(
            tabuleiroOponenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
        );
        tabuleiroOponenteLayout.setVerticalGroup(
            tabuleiroOponenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
        );

        chat.setColumns(20);
        chat.setRows(5);
        jScrollPane1.setViewportView(chat);

        painelCentral.setBackground(new java.awt.Color(255, 255, 255));
        painelCentral.setMaximumSize(new java.awt.Dimension(100, 100));
        btPoderEspecial.setText("Patada do Gato");

        painelLabelJogo.setBackground(new java.awt.Color(51, 51, 255));
        painelLabelJogo.setMaximumSize(new java.awt.Dimension(99, 99));
        painelLabelJogo.setMinimumSize(new java.awt.Dimension(99, 99));
        painelLabelJogo.setPreferredSize(new java.awt.Dimension(99, 99));
        javax.swing.GroupLayout painelLabelJogoLayout = new javax.swing.GroupLayout(painelLabelJogo);
        painelLabelJogo.setLayout(painelLabelJogoLayout);
        painelLabelJogoLayout.setHorizontalGroup(
            painelLabelJogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 107, Short.MAX_VALUE)
        );
        painelLabelJogoLayout.setVerticalGroup(
            painelLabelJogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 164, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout painelCentralLayout = new javax.swing.GroupLayout(painelCentral);
        painelCentral.setLayout(painelCentralLayout);
        painelCentralLayout.setHorizontalGroup(
            painelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btPoderEspecial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(painelLabelJogo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
        );
        painelCentralLayout.setVerticalGroup(
            painelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelCentralLayout.createSequentialGroup()
                .addComponent(painelLabelJogo, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btPoderEspecial, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        btEnviarMensagem.setText("Enviar");

        //areaDeConfiguracaoDeNavio.setBackground(new java.awt.Color(102, 51, 255));
        javax.swing.GroupLayout areaDeConfiguracaoDeNavioLayout = new javax.swing.GroupLayout(areaDeConfiguracaoDeNavio);
        areaDeConfiguracaoDeNavio.setLayout(areaDeConfiguracaoDeNavioLayout);
        areaDeConfiguracaoDeNavioLayout.setHorizontalGroup(
            areaDeConfiguracaoDeNavioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 619, Short.MAX_VALUE)
        );
        areaDeConfiguracaoDeNavioLayout.setVerticalGroup(
            areaDeConfiguracaoDeNavioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
       /* painelControle.setBackground(java.awt.Color.BLACK);
        javax.swing.GroupLayout painelControleLayout = new javax.swing.GroupLayout(painelControle);
        painelControle.setLayout(painelControleLayout);
        painelControleLayout.setHorizontalGroup(
            painelControleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 619, Short.MAX_VALUE)
        );
        painelControleLayout.setVerticalGroup(
            painelControleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );*/
        
        //painelControle.add(areaDeConfiguracaoDeNavio);
        
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 507, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btEnviarMensagem, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(33, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(areaDeConfiguracaoDeNavio, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(meuTabuleiro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(painelCentral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tabuleiroOponente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(19, 19, 19))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tabuleiroOponente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(meuTabuleiro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(painelCentral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addComponent(areaDeConfiguracaoDeNavio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btEnviarMensagem, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        txfMensagem.setBounds(45,670,200,40);
        add(txfMensagem);
    }// </editor-fold>                        
    
    /*public void trocarPaineis(){
        
        remove(areaDeConfiguracaoDeNavio);
        //LayoutManager lm = areaDeConfiguracaoDeNavio.getLayout();
        javax.swing.GroupLayout dadosRedeLayout = new javax.swing.GroupLayout(dadosRede);
        dadosRede.setLayout(dadosRedeLayout);
        dadosRedeLayout.setHorizontalGroup(
                dadosRedeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 619, Short.MAX_VALUE)
                );
        dadosRedeLayout.setVerticalGroup(
                dadosRedeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 100, Short.MAX_VALUE)
                );
        //areaDeConfiguracaoDeNavio = null;
        //dadosRede.setLayout(lm);
        //validate();
        javax.swing.JPanel p = new javax.swing.JPanel();
        p.setBackground(java.awt.Color.BLUE);
       
        javax.swing.GroupLayout pL = new javax.swing.GroupLayout(p);
        p.setLayout(pL);
        pL.setHorizontalGroup(
                pL.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 619, Short.MAX_VALUE)
                );
        pL.setVerticalGroup(
                pL.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 100, Short.MAX_VALUE)
                );
         this.add(p);
       validate();
       SwingUtilities.updateComponentTreeUI(this);
       //this.update(this.getGraphics());
       repaint();
    }*/
    
    // Declaração de variáveis - não modifique
    private javax.swing.JTextField txfMensagem;
    private javax.swing.JPanel painelControle;
    private AreaCentral areaDeConfiguracaoDeNavio;
    private javax.swing.JButton btEnviarMensagem;
    private javax.swing.JButton btPoderEspecial;
    private javax.swing.JTextArea chat;
    private javax.swing.JScrollPane jScrollPane1;
    private TabuleiroJogador meuTabuleiro;
    private javax.swing.JPanel painelCentral;
    private javax.swing.JPanel painelLabelJogo;
    private TabuleiroInimigo tabuleiroOponente;
    private DadosRede dadosRede;
    // Fim da declaração de variáveis                   
    
}